# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7865fec1c9275142374aa4432622740ec6c642f9e4319fc36d2a7cd931415ecfc6481bb9824ee4d13c036d3c0add1a125ad5cead9b3dcc8754c9d9303db5e660

test:
  secret_key_base: e13b77e11447921ef47e2d088f51130190bc72638670e491b778a7aabcaf5268717e2adc4d990bdf9ce40f6f19ccd0ff1f00d985376dda12a20e76b641d8ce75

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
